# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-14 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160814_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
