# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 05:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20160729_0514'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='joined',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 7, 29, 5, 27, 23, 830600, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
