# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 04:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20160815_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='for_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='app.Commentable'),
        ),
    ]
