# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 05:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_userprofile_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='joined',
        ),
    ]
