# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20160815_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='available',
            name='tags',
            field=models.ManyToManyField(blank=True, to='app.Tag'),
        ),
        migrations.AlterField(
            model_name='comment_answer',
            name='text',
            field=models.TextField(verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='comment_available',
            name='text',
            field=models.TextField(verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='comment_event',
            name='text',
            field=models.TextField(verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='comment_question',
            name='text',
            field=models.TextField(verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='comment_story',
            name='text',
            field=models.TextField(verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='comment_wanted',
            name='text',
            field=models.TextField(verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(blank=True, to='app.Tag'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, to='app.Tag'),
        ),
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, to='app.Tag'),
        ),
        migrations.AlterField(
            model_name='story',
            name='tags',
            field=models.ManyToManyField(blank=True, to='app.Tag'),
        ),
        migrations.AlterField(
            model_name='wanted',
            name='tags',
            field=models.ManyToManyField(blank=True, to='app.Tag'),
        ),
    ]
