# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_userprofile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='moderator',
            field=models.BooleanField(default=False),
        ),
    ]
