# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20160815_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='oneliner',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='interests',
            field=models.ManyToManyField(blank=True, to='app.Tag'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_text',
            field=models.CharField(max_length=500, null=True, verbose_name='Describe yourself'),
        ),
    ]
