# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20160815_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='campus',
            field=models.CharField(blank=True, choices=[('KTR', 'Kattankulathur'), ('VDP', 'Vadapalani'), ('RMP', 'Ramapuram'), ('NCR', 'NCR'), ('SKM', 'Sikkim')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='course',
            field=models.CharField(blank=True, choices=[('B.Tech', 'B.Tech'), ('M.Tech', 'M.Tech'), ('Phd', 'Phd')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, choices=[('CSE', 'CSE'), ('IT', 'IT'), ('ECE', 'ECE'), ('ITC', 'ITC'), ('Mech', 'Mech')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_text',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Describe yourself'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='register_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='year',
            field=models.IntegerField(blank=True, choices=[('I', 1), ('II', 2), ('III', 3), ('IV', 4), ('V', 5)], null=True),
        ),
    ]
