# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20160815_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(default='profiles/default.jpg', null=True, upload_to='profiles'),
        ),
    ]
