# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 19:50
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20160816_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=imagekit.models.fields.ProcessedImageField(default='profiles/default.jpg', upload_to='profiles'),
        ),
    ]
