# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 16:00
from __future__ import unicode_literals

from django.db import migrations
import django_markdown.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20160821_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=django_markdown.models.MarkdownField(),
        ),
        migrations.AlterField(
            model_name='available',
            name='text',
            field=django_markdown.models.MarkdownField(),
        ),
        migrations.AlterField(
            model_name='comment_answer',
            name='text',
            field=django_markdown.models.MarkdownField(verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='comment_available',
            name='text',
            field=django_markdown.models.MarkdownField(verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='comment_event',
            name='text',
            field=django_markdown.models.MarkdownField(verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='comment_question',
            name='text',
            field=django_markdown.models.MarkdownField(verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='comment_story',
            name='text',
            field=django_markdown.models.MarkdownField(verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='comment_wanted',
            name='text',
            field=django_markdown.models.MarkdownField(verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='event',
            name='text',
            field=django_markdown.models.MarkdownField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='text',
            field=django_markdown.models.MarkdownField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=django_markdown.models.MarkdownField(),
        ),
        migrations.AlterField(
            model_name='story',
            name='text',
            field=django_markdown.models.MarkdownField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_text',
            field=django_markdown.models.MarkdownField(blank=True, max_length=500, null=True, verbose_name='Describe yourself'),
        ),
        migrations.AlterField(
            model_name='wanted',
            name='text',
            field=django_markdown.models.MarkdownField(),
        ),
    ]
