# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 15:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20160822_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment_event',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='comment_event',
            name='for_item',
        ),
        migrations.RemoveField(
            model_name='event',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='event',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='event',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Comment_Event',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
