# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django_markdown.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20160823_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='App_Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=20, unique=True)),
                ('text', django_markdown.models.MarkdownField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
