# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 19:00
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_userprofile_num_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(default='projects/default.jpg', upload_to='projects'),
        ),
    ]
