# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 19:04
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20160825_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='projects/default.jpg', null=True, upload_to='projects'),
        ),
    ]
