# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 21:46
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20160827_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='projects/default.jpg', null=True, upload_to='projects'),
        ),
    ]
