# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 22:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_markdown.models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20160827_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, unique=True, verbose_name='your name, dept and year')),
                ('text', django_markdown.models.MarkdownField()),
            ],
        ),
        migrations.AlterField(
            model_name='notification',
            name='url',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Dept'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='profiles/default.jpg', upload_to='profiles'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='year',
            field=models.IntegerField(blank=True, choices=[(1, 'I'), (2, 'II'), (3, 'III'), (4, 'IV'), (5, 'V')], null=True),
        ),
    ]
