# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20160829_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='title',
            field=models.CharField(max_length=50, unique=True, verbose_name='your email'),
        ),
        migrations.RemoveField(
            model_name='tag',
            name='dept',
        ),
        migrations.AddField(
            model_name='tag',
            name='dept',
            field=models.ManyToManyField(blank=True, to='app.Dept'),
        ),
    ]
