# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20160903_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='dept',
            field=models.ManyToManyField(blank=True, null=True, to='app.Dept', verbose_name='related departments (hold shift for multiple)'),
        ),
    ]
