# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 09:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20160915_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='last_active',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
