# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-15 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_userprofile_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Tag Name'),
        ),
    ]
